### ISSUE TITLE
💣 TU plantés

### ISSUE THREAD

**Issue by adriens** [opt-nc/domaine-nc-action#26]
![image](https://user-images.githubusercontent.com/5235127/151739814-e92d694f-3584-46c4-b941-8c228b6164e9.png)

**Comment by adriens** [comment]
C'est pas lié à la dispo de l'API ❔  @Dougniel

**Comment by Dougniel** [comment]
@adriens , c'est du moqué donc théoriquement non

**Comment by Dougniel** [comment]
@adriens , théoriquement non c'est un test moqué

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/151740889-b245ec25-207c-4c0c-bafe-94173d56bc49.png)

**Comment by Dougniel** [comment]
@adriens , si c'est sûrement ça, j'avais oublié que j'avais fait un test d"intégration aussi et vue le temps que ça prends, ça ressemble à un timeout

**Comment by Dougniel** [comment]
@adriens, voci le retour de RapidAPI :
<img width="950" alt="image" src="https://user-images.githubusercontent.com/39691264/151741879-d01fe0e1-925e-45d2-9df4-4cd2e0df1841.png">

**Comment by adriens** [comment]
Yes, c'est ce que je craignais, y'a eu un changement d'IP sur AWS. Je me mets dessus

**Comment by adriens** [comment]
Mais si tu mockes, pourquoi es-tu impacté sur la non dispo de l'API @Dougniel  ❔

**Comment by adriens** [comment]
API restorée : tu confirmes @Dougniel 🙏 ❔

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/151879493-09a96c70-99fc-44d6-be32-00d81032c7ee.png)

**Comment by Dougniel** [comment]
> Mais si tu mockes, pourquoi es-tu impacté sur la non dispo de l'API @Dougniel ❔

cf https://github.com/opt-nc/domaine-nc-action/issues/26#issuecomment-1025383206

**Comment by Dougniel** [comment]
C'est good :
<img width="783" alt="image" src="https://user-images.githubusercontent.com/39691264/151880224-4f413725-f411-475b-80ea-1d968fc1fa1b.png">

**Comment by adriens** [comment]
👏
