### ISSUE TITLE
🎥 Please drop a video demo of how to configure é use the GH Actions 🕹️ 

### ISSUE THREAD

**Issue by adriens** [opt-nc/domaine-nc-action#36]
Idea os scenario : 

1. Create an empty repo
2. Configure for a given domain name
3. Trigger action
4. See the issue coming

**Comment by Dougniel** [comment]
@adriens, bon j'ai essayé de mettre le plus d'enthousiasme possible pour faire cette vidéo, je ne sais pas si ça va être suffisant ! En tous cas je pense avoir fait concis

La repo que j'ai utilisé dans la demo est ici: https://github.com/opt-nc/domaine-nc-test si elle ne te semble pas utile je la supprime

La vidéo est ici : https://optncl-my.sharepoint.com/:v:/g/personal/dsantos_opt_nc/EchBvdnjyORItMqPNv3_g1QBZ_6SogjKhZ4AgNIyAlaK7Q?e=atuo7Q

**Comment by adriens** [comment]
Super @Dougniel , merci, je vais pouvoir valroiser ce travail

:warning: Tu as pu regénérer ton secret sur rapidAPI après ? C'est une question que je me pose depuis un petit moment ...

**Comment by adriens** [comment]
C top d'avoir montré la partie RapidAPI :clap:

**Comment by adriens** [comment]
Je vais pouvoir me mettre sur #16

**Comment by Dougniel** [comment]
> Super @Dougniel , merci, je vais pouvoir valroiser ce travail
> 
> ⚠️ Tu as pu regénérer ton secret sur rapidAPI après ? C'est une question que je me pose depuis un petit moment ...

Olà attends 🙅, je viens de me rendre compte que j'ai posté ma vidéo brute et non pas celle ou je devais couper certains passages (notamment je me répète lorsque je fais des erreurs) et justement la partie rapid api je voulais pas la mettre car on voit mont secret et on pourrait le réutiliser !!

**Comment by adriens** [comment]
OUi, j'ai coupé le début et un peu la fin.

Ben ok, j'attends la nouvelle version.

Actuellement tu répètes trois fois "les secrets".

**Comment by adriens** [comment]
Cherche tout de même à voir si tu peux as regénérer ton secret 🙏  car ça arrivera forcément.

**Comment by Dougniel** [comment]
> Cherche tout de même à voir si tu peux as regénérer ton secret 🙏 car ça arrivera forcément.

Oui c'est ce que j'ai finalement préféré faire plutôt que d'essayer de flouter la clé dans la vidéo ! Je l'ai tout de même mis à jour en coupant les passages superflus, le lien reste le même 🚀

**Comment by Dougniel** [comment]
> OUi, j'ai coupé le début et un peu la fin.
> 
> Ben ok, j'attends la nouvelle version.
> 
> Actuellement tu répètes trois fois "les secrets".

Lorsque je me foire, je répète comme ça je coupe ensuite au montage

**Comment by adriens** [comment]
Du coup je rete sur la version actuelle. C'est psa si grave pour les secrets. J'ai coupé le début et la fin, c'est très bien.
Inutile de passer davanatage de temps là-dessus.

**Comment by Dougniel** [comment]
> Du coup je rete sur la version actuelle. C'est psa si grave pour les secrets. J'ai coupé le début et la fin, c'est très bien.
> Inutile de passer davanatage de temps là-dessus.

Pourquoi, tu n'as pas la dernière version que j'ai raccourci à 3m11s ? Si tu re-charge le lien tu devrais l'avoir?

**Comment by adriens** [comment]
J'attendais lepost d'un ouveau lien...pas l update , du coup j'ai pas capté. C'est pas grave, j'ai rien publié, je avais retravailler la video en conséqience avec la nouvelle video.

**Comment by adriens** [comment]
Elle est super compacte et complète : je m'y colle de suite. :zap:

**Comment by adriens** [comment]
J'ai juste eu à couper la partie ou tu arrêtes l'enregistrement.

3' pour la démo c'est au top :heavy_heart_exclamation:  Je vais travailler sur le POST DEV.to pour faire propre autour et mettre du contexte.

je vais aussi faire u ticket pour la repo des alertes. J'ai une idée qui fait son chemin. Je ferai une issue bien propre pour cela et ça devrait être très rapide à implémenter.

Merci pour le super conteu @Dougniel :muscle:  :heart_eyes_cat:

**Comment by adriens** [comment]
J ferai un teasing ce vendredi et enverrai le contenu semaine prochaine :rocket:

**Comment by Dougniel** [comment]
> J'ai juste eu à couper la partie ou tu arrêtes l'enregistrement.
> 
> 3' pour la démo c'est au top ❣️ Je vais travailler sur le POST DEV.to pour faire propre autour et mettre du contexte.
> 
> je vais aussi faire u ticket pour la repo des alertes. J'ai une idée qui fait son chemin. Je ferai une issue bien propre pour cela et ça devrait être très rapide à implémenter.
> 
> Merci pour le super conteu @Dougniel 💪 😻

Oui m'enfin je me répétai à plusieurs reprises dans cette vidéo brute pour pouvoir recouper au montage, c'est super désagréable pour les téléspectateurs 🤣

**Comment by adriens** [comment]
Je t'ai fait l'issue pour la repo des domaines de l'opt.
