### ISSUE TITLE
❌ Les TU ne passent plus - HTTP 403

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/domaine-nc-action#93]
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/39691264/193807012-2848ceee-34b9-4ac7-a9e1-fd03c0529e1c.png">

**Comment by Dougniel** [comment]
Block #87
Block #39

**Comment by Dougniel** [comment]
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/39691264/193809635-1bace846-f9be-49ef-829f-cc3c793e2a37.png">

Le token a expiré ou n'est plus abonné - je pense que le token paramètre est mon perso, va falloir le changer @adriens

**Comment by adriens** [comment]
> pour avancer, j'utilise mon perso

Tu peux en avoir plusieurs, y'a une notion d'applicaiton, tu verras, ça facilite les choses.

**Comment by Dougniel** [comment]
> Tu peux en avoir plusieurs, y'a une notion d'applicaiton, tu verras, ça facilite les choses.

Je préfères ne pas avoir une de mes clés perso à ce niveau, un jour je pourrais me débarrasser de mon compte RAPID API sans penser aux conséquences ! Même problématique qu'avec la logique des tokens PAT de GitHub
